### ISSUE TITLE
Enigma 2: VU+ Solo SE: OpenPli: HBB TV plugin remote volume and mute keys not working.

### ISSUE THREAD

**Issue by rocco99222** [mitxp/HbbTV-Testsuite#38]
Can thay solved it? Thanks!

**Comment by mitxp** [comment]
Hi, I don't really understand what you mean by this. I need a more concrete description here.
- What exactly is going wrong?
- What is the expected outcome?
- Which part of the specification are your refering to?

Closing this ticket as both volume keys and mute key is outside of HbbTV specification, so this can be neither tested nor be a problem with the HbbTV testsuite.

**Comment by rocco99222** [comment]
No remote key working exsepts the HBB TV control keys.

**Comment by mitxp** [comment]
I'm still not sure what you mean. Especially I don't know what you mean by "remote key". I checked the keyset value and, by default, we register the following keys:
- Navigation keys (left, right, up, down, OK)
- Color keys (reg, green, yellow, blue)

All other keys should go to the terminal (i.e. have no affect on the application). So, for example, you should be able to change the channel by using the number keys. This is expected behaviour. If you do not see it on your device, it might be a problem with your device. Again, to answer your question, I need this information:
- What do you do exactly? (step by step procedure)
- What exactly is going wrong? (please explain in detail what happens)
- What is the expected outcome? (please explain in detail what you would expect to happen)
- Which part of the specification are your refering to?

Without this information, I am unable to process your request.

**Comment by rocco99222** [comment]
Remote the VU+ remote: https://static.webshopapp.com/shops/120912/files/056233724/vu-extra-afstandsbediening-2-in-1-kleur-zwart.jpg

@ HBB-TV can't mute and control sound volume with it.

**Comment by mitxp** [comment]
This is a problem with your remote control or with your device. It's not a problem with the test suite.

Sorry, please contact your device manufacturer. Muting and sound volume control is not part of HbbTV.
